Fix error Jinja variable 'str object' has no attribute 'host'
Attempting to deploy php/application.php.dist in Salt results in the
following error: Unable to manage file: Jinja variable 'str object' has
no attribute 'host'.

This was caused by the php/application.php.dist expecting the Multicraft
SMTP information to be available though pillars.  This file has been
updated to instead use the vault.read_secret module to get the data from
Vault directly.